server:
  port: 8000

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

  profiles:
    active: eureka, security
  config:
    import: optional:configserver:http://localhost:8200


