server:
  port: 8000

spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: route1
          uri: lb://product-service
          predicates:
            - Path=/produto/**
          filters:
            - StripPrefix=1

        - id: route2
          uri: lb://my-list-service
          predicates:
            - Path=/minha-lista/**
          filters:
            - StripPrefix=1

  profiles:
    active: eureka, security
  config:
    import: optional:configserver:http://localhost:8200


