server:
  port:8300

spring:
  application:
    name: product-service

springdoc:
  swagger-ui:
    path: documentacao

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8100/eureka/